"""initial schema: languages, data, labels

Revision ID: 5e519a099282
Revises: 
Create Date: 2026-06-20 13:05:20.991624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e519a099282'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'audio', name='datatype'), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_language_id'), 'data', ['language_id'], unique=False)
    op.create_index(op.f('ix_data_name'), 'data', ['name'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_data_id'), 'labels', ['data_id'], unique=False)
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.drop_index(op.f('ix_labels_data_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_data_name'), table_name='data')
    op.drop_index(op.f('ix_data_language_id'), table_name='data')
    op.drop_table('data')
    # Postgres keeps the native enum type after the table is dropped; remove it
    # explicitly so a later re-upgrade doesn't fail with "type already exists".
    sa.Enum(name='datatype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
